# Site settings
author: Dhrubo Talukder
title: Chronicles of an aspiring Software Engineer
header-img: img/home-bg.png
email: dhrubo.dh@gmail.com
copyright_name: Dhrubo Talukder
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Dhrubot

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
